version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    minimum-release-age: 3
    ignore:
      - dependency-name: "@biomejs/biome"
